language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - python setup.py install
  - pip install -r requirements_test.txt

script:
  - ./run_tests

deploy:
  provider: pypi
  user: sensu_plugins
  password:
    secure: l84nSfeFo2b4ZbOBC3HbH8MnYxV9PMO16HIgGs3goXsc7RFMgB6bXV0h/jf9vj1aoZeVe4VyKPQVaZ1XLGz/tF2rZfad+CaXdkzwqvTnU33YQNKu26yocANTucC72nnfwJ+WQMGVUr/jBejhRL+UI9tpf8DXkM4LshOiXMkCeH4ebhMHlQAxuxZZPkbnD4EkpHV9aS2prb+5xhPrZwBDeJO5yukA70dO2wlGsPSkwCig+kRVInbReOp1+74PsEa4Vhj/2YgRV6DfVt+Xn1Pi40neVRSrkE3RQVDVRT6Sx8J0SrYdj0jWqCFnKaPgCr5PL25F31x5JaqV3fGTmPE3wxhsUXuUXBaHcYhwqDJ1c2gffqiz7HtDD1KebJa4NijXbgXnXi7IdvIuB6DvSGpPQYaA3LuFRYnJZjrSmq09TkvM6JQme9hfHkSjbxP7M68hfYztnba7ouY9nPP9iXCIqKjgEpqtaSwL0cf0747xW3EG35u327MwfGOj6DeJEAaHxnl2a7xCCFX+yZBe/lGxmlbFJjHCj1N3UJG6G0wDLdGk/K7CAMXvpmsANoyMm/IOFqjUSbSCam+RvV0sqe+2Sthu+yUYVxHHYmOHtyLnHsB/kIXVHJO6p5b01ZsZD1wKWwd4wnyhRM4j76izwB+wIQ9WQebAbR0r4ISxMBkNbug=
  on:
    tags: true
    branch: master
